# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "paris"
  fuzz = { runs = 10, max_test_rejects = 100_000 }
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  solc = "0.8.23"
  src = "src"
  test = "test"
  libs = ["lib"]
